// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZFCvETDjjoLTGkFkIapdTu8J7HXBDOa0',
    appId: '1:605889883141:web:58a3c2645f65a7c7e2806c',
    messagingSenderId: '605889883141',
    projectId: 'proyek-todolist-firebase',
    authDomain: 'proyek-todolist-firebase.firebaseapp.com',
    storageBucket: 'proyek-todolist-firebase.appspot.com',
    measurementId: 'G-YDCLN11R0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA833TGLGH1ceyoU7M1rbgHX7hptZbgt2E',
    appId: '1:605889883141:android:2e52774addd4d139e2806c',
    messagingSenderId: '605889883141',
    projectId: 'proyek-todolist-firebase',
    storageBucket: 'proyek-todolist-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZCD5epTsvv40uU9zFqS6FmUKFckO2APA',
    appId: '1:605889883141:ios:4e0d82f00e259ba9e2806c',
    messagingSenderId: '605889883141',
    projectId: 'proyek-todolist-firebase',
    storageBucket: 'proyek-todolist-firebase.appspot.com',
    iosBundleId: 'com.example.proyekTodolistFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZCD5epTsvv40uU9zFqS6FmUKFckO2APA',
    appId: '1:605889883141:ios:42518c92d7a6c3d4e2806c',
    messagingSenderId: '605889883141',
    projectId: 'proyek-todolist-firebase',
    storageBucket: 'proyek-todolist-firebase.appspot.com',
    iosBundleId: 'com.example.proyekTodolistFirebase.RunnerTests',
  );
}
